### PR TITLE
Update rules_docker pin.

### PR DESCRIPTION
**Pull request by xingao267**

### CODE REVIEW

**Comment by xingao267** [comment]
Updated to the latest version of rules_docker, which introduces some changes and fixes.

One fix is the latest rules_docker include the fix in container_structure_test (GoogleContainerTools/container-structure-test#146) which improper formatted yaml file will cause the tests to pass. Some tests that previously pass (false negatively) now fail. I fixed the broken yaml files. Most tests are fine except two tests (//tests/ubuntu:ubuntu_test, //tests/ubuntu:ubuntu_18_test) complain that the `cmd` in the image does not match those expected in the yaml file. I'm not sure if it's the issue in the image or just the test yamls need to be updated. PTAL @tejal29 @dlorenc .

**Comment by dlorenc** [comment]
Looks like something broke in the build:

```shell
+ image_id=6e2686bb434b5ef2d43761169b6b4b2d951b95cf838578f6a2083a9a16fb8f18
+ docker load -i bazel-out/k8-fastbuild/bin/tests/package_managers/gpg_image.key.tar
++ docker run -d 6e2686bb434b5ef2d43761169b6b4b2d951b95cf838578f6a2083a9a16fb8f18 sh -c 'apt-get update && apt-get install -y -q gnupg && for file in /gpg/*; do apt-key add $file; done'
+ id=860551dd3cb4686007cba5ef3cadb07a9fa34b4a2c53c9cf29f072fcbb4eedc7
+ docker wait 860551dd3cb4686007cba5ef3cadb07a9fa34b4a2c53c9cf29f072fcbb4eedc7
+ docker cp 860551dd3cb4686007cba5ef3cadb07a9fa34b4a2c53c9cf29f072fcbb4eedc7:/etc/apt/trusted.gpg bazel-out/k8-fastbuild/bin/tests/package_managers/gpg_image-trusted.gpg
Error response from daemon: Could not find the file /etc/apt/trusted.gpg in container 860551dd3cb4686007cba5ef3cadb07a9fa34b4a2c53c9cf29f072fcbb4eedc7
```

**Comment by xingao267** [comment]
@dlorenc looks like it's just a flake.

**Comment by tejal29** [comment]
hmm looks like docker wait is not deterministic for this.
```
'apt-get update && apt-get install -y -q gnupg && for file in /gpg/*; do apt-key add $file; done'
``1

**Pull request merged**
