### PR TITLE
Fix Bazel compatible issues.

### PR DESCRIPTION
**Pull request by xingao267**
- single_file is deprecated.
- new_file is deprecated.
- template_action is deprecated.

### CODE REVIEW

**Comment by xingao267** [comment]
@sharifelgamal @nkubala

**Comment by xingao267** [comment]
@tejal29

**Comment by laurentlb** [comment]
Thanks for doing it, I just ran into this problem too.
This PR looks good to me.

cc @donmccasland

**Comment by xingao267** [comment]
Friendly ping~ Can someone retrigger the Kokoro tests? The failures do not look like related to this change.

**Pull request merged**
