### PR TITLE
enable passing additional flags to docker run command in run_and_extract

### PR DESCRIPTION
**Pull request by nlopezgi**
* modified existing test to add new attribute docker_run_flags
* exposed the build script as an output so that tests can validate
its contents
* added test that verifies build script contains docker_run_flags

### CODE REVIEW

**Comment by nlopezgi** [comment]
@tejal29 could you please review? thanks!

**Comment by tejal29** [comment]
The kokoro run failed because the commit is not signed.
```
+ echo 'Latest commit not signed. Checking for tags.'
Latest commit not signed. Checking for tags.
++ git tag --points-at HEAD
+ tag=
+ [[ -z '' ]]
+ echo 'No tags pointing at HEAD!.'
No tags pointing at HEAD!.
+ exit 1
```

**Comment by tejal29** [comment]
@dlorenc or @sharifelgamal can you tag this commit and sign? Sorry i don't have the key on my laptop.

**Comment by sharifelgamal** [comment]
If the signing is the only failure then this can be safely merged.

**Comment by nlopezgi** [comment]
thanks a lot @sharifelgamal !

**Pull request merged**
